### ISSUE TITLE
how to contibute?

### ISSUE THREAD

**Issue by mibrahimdev** [gadc-russia/ud851-Sunshine-Kotlin-SlackTeam#72]
Hello guys, I really like the idea, but how to contribute to it, who assign tasks? an update to the README file will help to make things more organized.
thanks

**Comment by AndyRadionov** [comment]
Hey, @MohamedISoliman its kinda closet project for our slack team. Sorry. :-)

**Comment by mibrahimdev** [comment]
@AndyRadionov But I got invitation via Slack Udacity challenge

**Comment by AndyRadionov** [comment]
Heh. Project is not really active now. It started in russian section of Android-developer google scholarship program. Now I'm the only one who continued it. I will try to clarify about your contribution.

**Comment by AndyRadionov** [comment]
@stereoVibe , @viktorchukhantsev Hey guys! What you think about it?
